// <auto-generated/>
#pragma warning disable CS0618
using HraBot.ApiClient.Hello.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HraBot.ApiClient.Hello
{
    /// <summary>
    /// Builds and executes requests for operations under \hello
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HelloRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the HraBot.ApiClient.hello.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::HraBot.ApiClient.Hello.Item.HelloItemRequestBuilder"/></returns>
        public global::HraBot.ApiClient.Hello.Item.HelloItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::HraBot.ApiClient.Hello.Item.HelloItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HraBot.ApiClient.Hello.HelloRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HelloRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hello", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HraBot.ApiClient.Hello.HelloRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HelloRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/hello", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
