// <auto-generated/>
#pragma warning disable CS0618
using HraBot.ApiClient.Api.Chat;
using HraBot.ApiClient.Api.Feedback;
using HraBot.ApiClient.Api.Ping;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HraBot.ApiClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chat property</summary>
        public global::HraBot.ApiClient.Api.Chat.ChatRequestBuilder Chat
        {
            get => new global::HraBot.ApiClient.Api.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The feedback property</summary>
        public global::HraBot.ApiClient.Api.Feedback.FeedbackRequestBuilder Feedback
        {
            get => new global::HraBot.ApiClient.Api.Feedback.FeedbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ping property</summary>
        public global::HraBot.ApiClient.Api.Ping.PingRequestBuilder Ping
        {
            get => new global::HraBot.ApiClient.Api.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HraBot.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HraBot.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
