// <auto-generated/>
#pragma warning disable CS0618
using HraBot.ApiClient.Chat;
using HraBot.ApiClient.Feedback;
using HraBot.ApiClient.Ping;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HraBot.ApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HraBotApiClient : BaseRequestBuilder
    {
        /// <summary>The chat property</summary>
        public global::HraBot.ApiClient.Chat.ChatRequestBuilder Chat
        {
            get => new global::HraBot.ApiClient.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The feedback property</summary>
        public global::HraBot.ApiClient.Feedback.FeedbackRequestBuilder Feedback
        {
            get => new global::HraBot.ApiClient.Feedback.FeedbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ping property</summary>
        public global::HraBot.ApiClient.Ping.PingRequestBuilder Ping
        {
            get => new global::HraBot.ApiClient.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HraBot.ApiClient.HraBotApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HraBotApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
