// <auto-generated />
using System;
using HraBot.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HraBot.Core.Migrations
{
    [DbContext(typeof(HraBotDbContext))]
    [Migration("20260102220012_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HraBot.Core.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("NumMessages")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("HraBot.Core.Features.Feedback.MessageFeedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("text");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("MessageFeedbacks");
                });

            modelBuilder.Entity("HraBot.Core.Features.Feedback.MessageFeedbackItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("FeedbackItem")
                        .HasColumnType("smallint");

                    b.Property<byte>("FeedbackType")
                        .HasColumnType("smallint");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MessageFeedbackItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FeedbackItem = (byte)1,
                            FeedbackType = (byte)1,
                            ShortDescription = "no issues"
                        },
                        new
                        {
                            Id = 4L,
                            FeedbackItem = (byte)1,
                            FeedbackType = (byte)2,
                            ShortDescription = "incorrect"
                        },
                        new
                        {
                            Id = 5L,
                            FeedbackItem = (byte)1,
                            FeedbackType = (byte)2,
                            ShortDescription = "missing information"
                        },
                        new
                        {
                            Id = 6L,
                            FeedbackItem = (byte)1,
                            FeedbackType = (byte)2,
                            ShortDescription = "not applicable to question"
                        },
                        new
                        {
                            Id = 7L,
                            FeedbackItem = (byte)1,
                            FeedbackType = (byte)2,
                            ShortDescription = "not informed by citations"
                        },
                        new
                        {
                            Id = 8L,
                            FeedbackItem = (byte)1,
                            FeedbackType = (byte)2,
                            ShortDescription = "other"
                        },
                        new
                        {
                            Id = 2L,
                            FeedbackItem = (byte)2,
                            FeedbackType = (byte)1,
                            ShortDescription = "no issues"
                        },
                        new
                        {
                            Id = 9L,
                            FeedbackItem = (byte)2,
                            FeedbackType = (byte)2,
                            ShortDescription = "missing"
                        },
                        new
                        {
                            Id = 10L,
                            FeedbackItem = (byte)2,
                            FeedbackType = (byte)2,
                            ShortDescription = "incorrect"
                        },
                        new
                        {
                            Id = 11L,
                            FeedbackItem = (byte)2,
                            FeedbackType = (byte)2,
                            ShortDescription = "not applicable to question"
                        },
                        new
                        {
                            Id = 12L,
                            FeedbackItem = (byte)2,
                            FeedbackType = (byte)2,
                            ShortDescription = "other"
                        },
                        new
                        {
                            Id = 3L,
                            FeedbackItem = (byte)2,
                            FeedbackType = (byte)1,
                            ShortDescription = "no issues"
                        },
                        new
                        {
                            Id = 13L,
                            FeedbackItem = (byte)3,
                            FeedbackType = (byte)2,
                            ShortDescription = "too slow"
                        },
                        new
                        {
                            Id = 14L,
                            FeedbackItem = (byte)3,
                            FeedbackType = (byte)2,
                            ShortDescription = "other"
                        },
                        new
                        {
                            Id = 15L,
                            FeedbackItem = (byte)255,
                            FeedbackType = (byte)2,
                            ShortDescription = "other"
                        });
                });

            modelBuilder.Entity("HraBot.Core.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte?>("AiModel")
                        .HasColumnType("smallint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MessageFeedbackMessageFeedbackItem", b =>
                {
                    b.Property<long>("MessageFeedbackItemsId")
                        .HasColumnType("bigint");

                    b.Property<long>("MessageFeedbacksId")
                        .HasColumnType("bigint");

                    b.HasKey("MessageFeedbackItemsId", "MessageFeedbacksId");

                    b.HasIndex("MessageFeedbacksId");

                    b.ToTable("MessageFeedbackMessageFeedbackItem");
                });

            modelBuilder.Entity("HraBot.Core.Features.Feedback.MessageFeedback", b =>
                {
                    b.HasOne("HraBot.Core.Message", "Message")
                        .WithOne()
                        .HasForeignKey("HraBot.Core.Features.Feedback.MessageFeedback", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("HraBot.Core.Message", b =>
                {
                    b.HasOne("HraBot.Core.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MessageFeedbackMessageFeedbackItem", b =>
                {
                    b.HasOne("HraBot.Core.Features.Feedback.MessageFeedbackItem", null)
                        .WithMany()
                        .HasForeignKey("MessageFeedbackItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HraBot.Core.Features.Feedback.MessageFeedback", null)
                        .WithMany()
                        .HasForeignKey("MessageFeedbacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HraBot.Core.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
