// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace HraBot.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FeedbackContract : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The additionalComments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalComments { get; set; }
#nullable restore
#else
        public string AdditionalComments { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The importanceToTakeCommand property</summary>
        public byte? ImportanceToTakeCommand { get; set; }
        /// <summary>The messageFeedbackItemIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? MessageFeedbackItemIds { get; set; }
#nullable restore
#else
        public List<long?> MessageFeedbackItemIds { get; set; }
#endif
        /// <summary>The messageId property</summary>
        public long? MessageId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::HraBot.ApiClient.Models.FeedbackContract"/> and sets the default values.
        /// </summary>
        public FeedbackContract()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::HraBot.ApiClient.Models.FeedbackContract"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::HraBot.ApiClient.Models.FeedbackContract CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::HraBot.ApiClient.Models.FeedbackContract();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalComments", n => { AdditionalComments = n.GetStringValue(); } },
                { "importanceToTakeCommand", n => { ImportanceToTakeCommand = n.GetByteValue(); } },
                { "messageFeedbackItemIds", n => { MessageFeedbackItemIds = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
                { "messageId", n => { MessageId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("additionalComments", AdditionalComments);
            writer.WriteByteValue("importanceToTakeCommand", ImportanceToTakeCommand);
            writer.WriteCollectionOfPrimitiveValues<long?>("messageFeedbackItemIds", MessageFeedbackItemIds);
            writer.WriteLongValue("messageId", MessageId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
